### ISSUE TITLE
Peakfinder start and end date

### ISSUE THREAD

**Issue by axololtl1997** [epfl-lts2/sparkwiki#22]
Hello,
On the webpage, https://wiki-insights.epfl.ch/wikitrends/ you have shown the Wikipedia graph changing on a hourly basis. Could you tell me how that was obtained? For ex. if I try to adjust the start date and end date in PeakFinder.config to be the same in order to get the wiki graph for a certain day, I get a SeasonalTrendLoess error, and it can run only if the gap is at least two days How do I increase my granularity to hourly or daily?
Thanks, A.K.

**Comment by naspert** [comment]
Hi,
In order to remove the daily variations properly you need to have a certain amount of data to be able to do it... and IIRC in wikitrends, the raw data from wikipedia visits are displayed, whereas the activity graph is computed usually over a week or so.

**Comment by axololtl1997** [comment]
Thanks for the reply! On the website the activity graph does change with the hour, which is why I asked.
Also I have another question, when I run over a 24 hour period, the obtained articles are as expected but the Pearson correlation for 99% of the edges in the activity graph is 1.0, and there is very less variance in the edge weights, which is not expected (We expect some spread in the edge weights). Is this an expected phenomenon, and is there a way to fix this?

**Comment by naspert** [comment]
On the website, the only thing that changes when changing the hour are the *active* nodes. The graph stays identical, only the active nodes are highlighted. 24 hours seem short, and the high correlation is (kinda) expected because of the daily trend that cannot be removed (that is why we compute the graph for a full week, with 2 weeks prior data to have a working activity detection)
